name: publish
on: [create]
jobs:
  call-base-workflow:
    uses: ./.github/workflows/base-workflow.yml
  create-artifact:
    runs-on: ubuntu-latest
    needs: call-base-workflow
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v3
      - run: |
          CLEAN_VERSION=${GITHUB_REF//refs\/tags\/v/}
          sed -i.bak "s/__APPVERSION__/$CLEAN_VERSION/" src/api/*.py
          rm src/api/*.bak
          mkdir dist
          cp README.md LICENSE dist/
          mv src/* dist
          zip -qr dist.zip dist
      - uses: actions/upload-artifact@v3
        with:
          name: publish-artifact
          path: |
            dist.zip
  draft-release:
    runs-on: ubuntu-latest
    needs: create-artifact
    steps:
      - uses: actions/download-artifact@v4.1.7
        with:
          name: publish-artifact
      - run: |
          TAG=${GITHUB_REF//refs\/tags\//}
          ZIP_FILENAME="braviaremotecontrolapi-${TAG}.zip"
          mv dist.zip $ZIP_FILENAME
      - uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            *.zip
